name: Checking commit quality

on:
  push:
  pull_request:
    branches:
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: test
        run:  |
          npm ci
          npm install typescript
          npm run test
      - name: build frontend
        run: npm run build